# Generated by Django 6.0.3 on 2026-03-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorifu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuy_cds', models.PositiveIntegerField(default=0)),
                ('tuy_emb', models.PositiveIntegerField(default=0)),
                ('tuy_rob', models.PositiveIntegerField(default=0)),
                ('isol_cds', models.PositiveIntegerField(default=0)),
                ('isol_emb', models.PositiveIntegerField(default=0)),
                ('isol_rob', models.PositiveIntegerField(default=0)),
                ('antifeu_cds', models.PositiveIntegerField(default=0)),
                ('antifeu_emb', models.PositiveIntegerField(default=0)),
                ('antifeu_rob', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.article')),
            ],
        ),
    ]
