# Generated by Django 6.0.3 on 2026-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
