# Generated by Django 6.0.3 on 2026-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=50)),
                ('sous_groupe', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
                ('qte', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
