# Generated by Django 6.0.3 on 2026-03-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.equipement')),
            ],
        ),
    ]
