# Generated by Django 6.0.3 on 2026-03-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('systeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.systeme'),
        ),
    ]
