# Generated by Django 6.0.3 on 2026-03-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
        ('equipement', '0003_alter_equipement_groupe_alter_equipement_prix_and_more'),
        ('systeme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipement_articles', to='equipement.equipement'),
        ),
        migrations.AlterField(
            model_name='article',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systeme_articles', to='systeme.systeme'),
        ),
    ]
