# Generated by Django 6.0.3 on 2026-03-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_groupe_sous_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.groupe'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='sous_groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.sous_groupe'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sous_groupe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
