# Generated by Django 6.0.3 on 2026-03-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_alter_equipement_groupe_alter_equipement_prix_and_more'),
        ('systeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='systemtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='systemtype_equipement_lies', to='systeme.systemetype'),
        ),
    ]
