# Generated by Django 6.0.3 on 2026-03-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_equipement_systemtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='systemtype',
        ),
    ]
