# Generated by Django 6.0.3 on 2026-03-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('batiment', '0001_initial'),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('articles_lies', models.ManyToManyField(blank=True, related_name='systeme_types', to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='systemes_lies', to='article.article')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemes', to='batiment.local')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemes', to='projet.projet')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemes', to='systeme.systemetype')),
            ],
        ),
    ]
