# Generated by Django 6.0.3 on 2026-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_equipement_systemtype'),
        ('systeme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemetype',
            name='articles_lies',
        ),
        migrations.AddField(
            model_name='systemetype',
            name='equipements_lies',
            field=models.ManyToManyField(blank=True, related_name='systeme_types', to='equipement.equipement'),
        ),
    ]
