# Generated by Django 6.0.3 on 2026-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemetype',
            name='abreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='systemetype',
            name='prodouemis',
            field=models.CharField(choices=[('PROD', 'Production'), ('EMI', 'Emission')], default='PROD', max_length=4, verbose_name='Type'),
        ),
    ]
