# Generated by Django 6.0.3 on 2026-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0002_systemetype_abreviation_systemetype_prodouemis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeme',
            name='abreviation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
