# Generated by Django 6.0.3 on 2026-03-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cp', models.IntegerField(default=0)),
                ('rue', models.CharField(blank=True, max_length=50)),
                ('ville', models.CharField(blank=True, max_length=50)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments_batiment', to='projet.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etages', to='batiment.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('surface', models.FloatField(help_text='Surface en m²')),
                ('qint', models.FloatField(help_text='Température intérieure en °C')),
                ('qe', models.FloatField(help_text='Température extérieure en °C')),
                ('FT', models.FloatField(help_text='Flux thermique en W')),
                ('FV', models.FloatField(help_text='Flux ventilation en W')),
                ('Fg', models.FloatField(help_text='Flux gains en W')),
                ('FHL', models.FloatField(help_text='Flux chauffage en W')),
                ('fapostehl', models.FloatField(help_text='Flux aposté en W/m²')),
                ('nmin', models.FloatField(help_text="Taux de renouvellement d'air en h⁻¹")),
                ('etage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locals', to='batiment.etage')),
            ],
        ),
    ]
